---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml
  tasks:
    - name: Install base system package
      yum:
        name:
          - yum-utils
        state: latest
        
    - name: Firewalld disalbe/stop
      ansible.builtin.service:
        name: firewalld
        enabled: no
        state: stopped

    - name: Add docker to yum repository
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Install docker package
      yum:
        name:
          - docker-ce-{{ docker_version }}
          - docker-ce-cli-{{ docker_version }}
          - containerd.io
        state: present

    - name: Enable/Start the Docker Service
      ansible.builtin.service:
        name: docker
        enabled: yes
        state: started